### ISSUE TITLE
upload_file fails when --proxy option is passed

### ISSUE THREAD

**Issue by kherner** [fermitools/poms#25]
After setting up poms_client 4.5.2 in AL9 and also running 

export WEB_CONFIG=$(spack location -i poms-client@4.5.2%gcc@11.3.1)/bin/client.cf

I get the following error when adding the --proxy option to the upload_file command:
 

> dunegpvm13:~$ upload_file --experiment=dune --poms_role=analysis --proxy --vaulttoken
> ERROR:root:/cvmfs/fermilab.opensciencegrid.org/packages/common/poms-client/4.5.2/linux-almalinux9-x86_64_v2-gcc-11.3.1-hplsffixuxrbnnmlp5izlj4jxvqleapu/bin/upload_file: while getting proxy:
> Traceback (most recent call last):
>   File "/cvmfs/fermilab.opensciencegrid.org/packages/common/poms-client/4.5.2/linux-almalinux9-x86_64_v2-gcc-11.3.1-hplsffixuxrbnnmlp5izlj4jxvqleapu/bin/upload_file", line 98, in <module>
>     os.system("cigetcert -v -n -s %s" % config.get("FNAL", "fifebatch_server"))
>   File "/cvmfs/fermilab.opensciencegrid.org/packages/common/python/3.9.15/linux-scientific7-x86_64_v2-gcc-4.8.5-hg2ypaaupczilw2qbpuev2yg2k2rhevx/lib/python3.9/configparser.py", line 781, in get
>     d = self._unify_values(section, vars)
>   File "/cvmfs/fermilab.opensciencegrid.org/packages/common/python/3.9.15/linux-scientific7-x86_64_v2-gcc-4.8.5-hg2ypaaupczilw2qbpuev2yg2k2rhevx/lib/python3.9/configparser.py", line 1152, in _unify_values
>     raise NoSectionError(section) from None
> configparser.NoSectionError: No section: 'FNAL'

No issues when I omit the --proxy option. Looks like it's complaining about not being able to fine the proper fifebatch server name from the "FNAL" section of the config file, which doesn't exist.

**Comment by goodenou** [comment]
Since proxies are going away on April 30th we should get rid of --proxy option altogether.

**Comment by goodenou** [comment]
Check config file that we ship with the poms_client package as well.
